# This is a basic workflow that is manually triggered
name: 02 - Evento Issue
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    paths-ignore:
      - '*.md'
  issues:
    types: [opened]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Hola Gabriel
      run: echo "Hola gabriel!"
